# -*- coding: utf-8 -*-

import pandas as pd

# Read the pivot ready BOM generated by pythonBOM.py
pivot_ready_BOM = pd.read_csv('../BOM_pivot_ready.csv')

# Group the resulting df by the columns needed by construction per the 'playbook generator' tab in Sam's ss
playbook = pivot_ready_BOM.groupby(['item_name_parent_floor', 'Network Text Final', 'item_number', 'item_name'])

# Stack overflow solution for print groupby object to csv
# https://stackoverflow.com/questions/47602097/pandas-groupby-to-to-csv
playbook.sum().reset_index()[['item_name_parent_floor', 'Network Text Final', 'item_number', 'item_name']].to_csv('../playbookGenerator.csv')